/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CourseManager {
  export type CourseStruct = {
    id: BigNumberish;
    title: string;
    description: string;
    author: AddressLike;
    priceInYD: BigNumberish;
    totalEnrolled: BigNumberish;
    isActive: boolean;
    createdAt: BigNumberish;
  };

  export type CourseStructOutput = [
    id: bigint,
    title: string,
    description: string,
    author: string,
    priceInYD: bigint,
    totalEnrolled: bigint,
    isActive: boolean,
    createdAt: bigint
  ] & {
    id: bigint;
    title: string;
    description: string;
    author: string;
    priceInYD: bigint;
    totalEnrolled: bigint;
    isActive: boolean;
    createdAt: bigint;
  };

  export type PurchaseStruct = {
    courseId: BigNumberish;
    purchasedAt: BigNumberish;
  };

  export type PurchaseStructOutput = [courseId: bigint, purchasedAt: bigint] & {
    courseId: bigint;
    purchasedAt: bigint;
  };
}

export interface CourseManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkPurchase"
      | "courseCount"
      | "courseRevenue"
      | "courses"
      | "createCourse"
      | "getCourse"
      | "getUserPurchases"
      | "hasPurchased"
      | "owner"
      | "platformFeeRate"
      | "platformRevenue"
      | "purchaseCourse"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateCoursePrice"
      | "updatePlatformFeeRate"
      | "userPurchases"
      | "withdrawCourseRevenue"
      | "withdrawPlatformRevenue"
      | "ydToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CourseCreated"
      | "CoursePurchased"
      | "CourseUpdated"
      | "OwnershipTransferred"
      | "PlatformFeeUpdated"
      | "RevenueWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkPurchase",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "courseCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courseRevenue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "courses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCourse",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCourse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPurchases",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPurchased",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseCourse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCoursePrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userPurchases",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCourseRevenue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ydToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "checkPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "courseCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "courseRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "courses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCourse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserPurchases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCoursePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPurchases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCourseRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ydToken", data: BytesLike): Result;
}

export namespace CourseCreatedEvent {
  export type InputTuple = [
    courseId: BigNumberish,
    author: AddressLike,
    title: string,
    price: BigNumberish
  ];
  export type OutputTuple = [
    courseId: bigint,
    author: string,
    title: string,
    price: bigint
  ];
  export interface OutputObject {
    courseId: bigint;
    author: string;
    title: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CoursePurchasedEvent {
  export type InputTuple = [
    courseId: BigNumberish,
    student: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [courseId: bigint, student: string, price: bigint];
  export interface OutputObject {
    courseId: bigint;
    student: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CourseUpdatedEvent {
  export type InputTuple = [courseId: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [courseId: bigint, newPrice: bigint];
  export interface OutputObject {
    courseId: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFeeRate: BigNumberish];
  export type OutputTuple = [newFeeRate: bigint];
  export interface OutputObject {
    newFeeRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueWithdrawnEvent {
  export type InputTuple = [
    courseId: BigNumberish,
    author: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [courseId: bigint, author: string, amount: bigint];
  export interface OutputObject {
    courseId: bigint;
    author: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CourseManager extends BaseContract {
  connect(runner?: ContractRunner | null): CourseManager;
  waitForDeployment(): Promise<this>;

  interface: CourseManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkPurchase: TypedContractMethod<
    [user: AddressLike, courseId: BigNumberish],
    [boolean],
    "view"
  >;

  courseCount: TypedContractMethod<[], [bigint], "view">;

  courseRevenue: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  courses: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean, bigint] & {
        id: bigint;
        title: string;
        description: string;
        author: string;
        priceInYD: bigint;
        totalEnrolled: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  createCourse: TypedContractMethod<
    [title: string, description: string, priceInYD: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getCourse: TypedContractMethod<
    [courseId: BigNumberish],
    [CourseManager.CourseStructOutput],
    "view"
  >;

  getUserPurchases: TypedContractMethod<
    [user: AddressLike],
    [CourseManager.PurchaseStructOutput[]],
    "view"
  >;

  hasPurchased: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeRate: TypedContractMethod<[], [bigint], "view">;

  platformRevenue: TypedContractMethod<[], [bigint], "view">;

  purchaseCourse: TypedContractMethod<
    [courseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCoursePrice: TypedContractMethod<
    [courseId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  updatePlatformFeeRate: TypedContractMethod<
    [newFeeRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  userPurchases: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [[bigint, bigint] & { courseId: bigint; purchasedAt: bigint }],
    "view"
  >;

  withdrawCourseRevenue: TypedContractMethod<
    [courseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawPlatformRevenue: TypedContractMethod<[], [void], "nonpayable">;

  ydToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkPurchase"
  ): TypedContractMethod<
    [user: AddressLike, courseId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "courseCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "courseRevenue"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "courses"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean, bigint] & {
        id: bigint;
        title: string;
        description: string;
        author: string;
        priceInYD: bigint;
        totalEnrolled: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCourse"
  ): TypedContractMethod<
    [title: string, description: string, priceInYD: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCourse"
  ): TypedContractMethod<
    [courseId: BigNumberish],
    [CourseManager.CourseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPurchases"
  ): TypedContractMethod<
    [user: AddressLike],
    [CourseManager.PurchaseStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPurchased"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformRevenue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchaseCourse"
  ): TypedContractMethod<[courseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCoursePrice"
  ): TypedContractMethod<
    [courseId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePlatformFeeRate"
  ): TypedContractMethod<[newFeeRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userPurchases"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [[bigint, bigint] & { courseId: bigint; purchasedAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawCourseRevenue"
  ): TypedContractMethod<[courseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPlatformRevenue"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ydToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CourseCreated"
  ): TypedContractEvent<
    CourseCreatedEvent.InputTuple,
    CourseCreatedEvent.OutputTuple,
    CourseCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CoursePurchased"
  ): TypedContractEvent<
    CoursePurchasedEvent.InputTuple,
    CoursePurchasedEvent.OutputTuple,
    CoursePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "CourseUpdated"
  ): TypedContractEvent<
    CourseUpdatedEvent.InputTuple,
    CourseUpdatedEvent.OutputTuple,
    CourseUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RevenueWithdrawn"
  ): TypedContractEvent<
    RevenueWithdrawnEvent.InputTuple,
    RevenueWithdrawnEvent.OutputTuple,
    RevenueWithdrawnEvent.OutputObject
  >;

  filters: {
    "CourseCreated(uint256,address,string,uint256)": TypedContractEvent<
      CourseCreatedEvent.InputTuple,
      CourseCreatedEvent.OutputTuple,
      CourseCreatedEvent.OutputObject
    >;
    CourseCreated: TypedContractEvent<
      CourseCreatedEvent.InputTuple,
      CourseCreatedEvent.OutputTuple,
      CourseCreatedEvent.OutputObject
    >;

    "CoursePurchased(uint256,address,uint256)": TypedContractEvent<
      CoursePurchasedEvent.InputTuple,
      CoursePurchasedEvent.OutputTuple,
      CoursePurchasedEvent.OutputObject
    >;
    CoursePurchased: TypedContractEvent<
      CoursePurchasedEvent.InputTuple,
      CoursePurchasedEvent.OutputTuple,
      CoursePurchasedEvent.OutputObject
    >;

    "CourseUpdated(uint256,uint256)": TypedContractEvent<
      CourseUpdatedEvent.InputTuple,
      CourseUpdatedEvent.OutputTuple,
      CourseUpdatedEvent.OutputObject
    >;
    CourseUpdated: TypedContractEvent<
      CourseUpdatedEvent.InputTuple,
      CourseUpdatedEvent.OutputTuple,
      CourseUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "RevenueWithdrawn(uint256,address,uint256)": TypedContractEvent<
      RevenueWithdrawnEvent.InputTuple,
      RevenueWithdrawnEvent.OutputTuple,
      RevenueWithdrawnEvent.OutputObject
    >;
    RevenueWithdrawn: TypedContractEvent<
      RevenueWithdrawnEvent.InputTuple,
      RevenueWithdrawnEvent.OutputTuple,
      RevenueWithdrawnEvent.OutputObject
    >;
  };
}
