/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aaveIntegrationSol from "./AaveIntegration.sol";
export type { aaveIntegrationSol };
export type { CourseManager } from "./CourseManager";
export type { YDToken } from "./YDToken";
