/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AaveIntegrationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aavePool"
      | "annualYieldRate"
      | "calculateReward"
      | "claimReward"
      | "getUSDTBalance"
      | "getUserStakeInfo"
      | "getYDBalance"
      | "owner"
      | "renounceOwnership"
      | "stakeToAave"
      | "stakeYD"
      | "stakedAmount"
      | "swapETHToUSDT"
      | "swapRouter"
      | "swapYDToUSDT"
      | "totalStaked"
      | "transferOwnership"
      | "unstake"
      | "updateYieldRate"
      | "usdtAddress"
      | "userStakes"
      | "withdrawFromAave"
      | "withdrawUSDT"
      | "ydTokenAddress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RewardClaimed"
      | "StakedToAave"
      | "TokensSwapped"
      | "UserStaked"
      | "WithdrawnFromAave"
      | "YieldRateUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "aavePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "annualYieldRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUSDTBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStakeInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getYDBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakeToAave",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeYD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakedAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapETHToUSDT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapYDToUSDT",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unstake", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateYieldRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usdtAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userStakes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromAave",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUSDT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ydTokenAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "aavePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "annualYieldRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUSDTBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStakeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYDBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeToAave",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakeYD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapETHToUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapYDToUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateYieldRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usdtAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userStakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromAave",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ydTokenAddress",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedToAaveEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensSwappedEvent {
  export type InputTuple = [
    fromToken: AddressLike,
    toToken: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    fromToken: string,
    toToken: string,
    amountIn: bigint,
    amountOut: bigint
  ];
  export interface OutputObject {
    fromToken: string;
    toToken: string;
    amountIn: bigint;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserStakedEvent {
  export type InputTuple = [
    user: AddressLike,
    ydAmount: BigNumberish,
    usdtAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    ydAmount: bigint,
    usdtAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    ydAmount: bigint;
    usdtAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnFromAaveEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldRateUpdatedEvent {
  export type InputTuple = [newRate: BigNumberish];
  export type OutputTuple = [newRate: bigint];
  export interface OutputObject {
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AaveIntegration extends BaseContract {
  connect(runner?: ContractRunner | null): AaveIntegration;
  waitForDeployment(): Promise<this>;

  interface: AaveIntegrationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aavePool: TypedContractMethod<[], [string], "view">;

  annualYieldRate: TypedContractMethod<[], [bigint], "view">;

  calculateReward: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  claimReward: TypedContractMethod<[], [void], "nonpayable">;

  getUSDTBalance: TypedContractMethod<[], [bigint], "view">;

  getUserStakeInfo: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        ydAmount: bigint;
        usdtAmount: bigint;
        stakedAt: bigint;
        pendingReward: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getYDBalance: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  stakeToAave: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeYD: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  stakedAmount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  swapETHToUSDT: TypedContractMethod<
    [amountOutMinimum: BigNumberish],
    [bigint],
    "payable"
  >;

  swapRouter: TypedContractMethod<[], [string], "view">;

  swapYDToUSDT: TypedContractMethod<
    [amountIn: BigNumberish, amountOutMinimum: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  totalStaked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<[], [void], "nonpayable">;

  updateYieldRate: TypedContractMethod<
    [newRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  usdtAddress: TypedContractMethod<[], [string], "view">;

  userStakes: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        ydAmount: bigint;
        usdtAmount: bigint;
        stakedAt: bigint;
        lastClaimAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  withdrawFromAave: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  withdrawUSDT: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  ydTokenAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aavePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "annualYieldRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateReward"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getUSDTBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserStakeInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        ydAmount: bigint;
        usdtAmount: bigint;
        stakedAt: bigint;
        pendingReward: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getYDBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeToAave"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeYD"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakedAmount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "swapETHToUSDT"
  ): TypedContractMethod<[amountOutMinimum: BigNumberish], [bigint], "payable">;
  getFunction(
    nameOrSignature: "swapRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swapYDToUSDT"
  ): TypedContractMethod<
    [amountIn: BigNumberish, amountOutMinimum: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateYieldRate"
  ): TypedContractMethod<[newRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdtAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userStakes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        ydAmount: bigint;
        usdtAmount: bigint;
        stakedAt: bigint;
        lastClaimAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFromAave"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawUSDT"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ydTokenAddress"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "StakedToAave"
  ): TypedContractEvent<
    StakedToAaveEvent.InputTuple,
    StakedToAaveEvent.OutputTuple,
    StakedToAaveEvent.OutputObject
  >;
  getEvent(
    key: "TokensSwapped"
  ): TypedContractEvent<
    TokensSwappedEvent.InputTuple,
    TokensSwappedEvent.OutputTuple,
    TokensSwappedEvent.OutputObject
  >;
  getEvent(
    key: "UserStaked"
  ): TypedContractEvent<
    UserStakedEvent.InputTuple,
    UserStakedEvent.OutputTuple,
    UserStakedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawnFromAave"
  ): TypedContractEvent<
    WithdrawnFromAaveEvent.InputTuple,
    WithdrawnFromAaveEvent.OutputTuple,
    WithdrawnFromAaveEvent.OutputObject
  >;
  getEvent(
    key: "YieldRateUpdated"
  ): TypedContractEvent<
    YieldRateUpdatedEvent.InputTuple,
    YieldRateUpdatedEvent.OutputTuple,
    YieldRateUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardClaimed(address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "StakedToAave(address,uint256)": TypedContractEvent<
      StakedToAaveEvent.InputTuple,
      StakedToAaveEvent.OutputTuple,
      StakedToAaveEvent.OutputObject
    >;
    StakedToAave: TypedContractEvent<
      StakedToAaveEvent.InputTuple,
      StakedToAaveEvent.OutputTuple,
      StakedToAaveEvent.OutputObject
    >;

    "TokensSwapped(address,address,uint256,uint256)": TypedContractEvent<
      TokensSwappedEvent.InputTuple,
      TokensSwappedEvent.OutputTuple,
      TokensSwappedEvent.OutputObject
    >;
    TokensSwapped: TypedContractEvent<
      TokensSwappedEvent.InputTuple,
      TokensSwappedEvent.OutputTuple,
      TokensSwappedEvent.OutputObject
    >;

    "UserStaked(address,uint256,uint256,uint256)": TypedContractEvent<
      UserStakedEvent.InputTuple,
      UserStakedEvent.OutputTuple,
      UserStakedEvent.OutputObject
    >;
    UserStaked: TypedContractEvent<
      UserStakedEvent.InputTuple,
      UserStakedEvent.OutputTuple,
      UserStakedEvent.OutputObject
    >;

    "WithdrawnFromAave(address,uint256)": TypedContractEvent<
      WithdrawnFromAaveEvent.InputTuple,
      WithdrawnFromAaveEvent.OutputTuple,
      WithdrawnFromAaveEvent.OutputObject
    >;
    WithdrawnFromAave: TypedContractEvent<
      WithdrawnFromAaveEvent.InputTuple,
      WithdrawnFromAaveEvent.OutputTuple,
      WithdrawnFromAaveEvent.OutputObject
    >;

    "YieldRateUpdated(uint256)": TypedContractEvent<
      YieldRateUpdatedEvent.InputTuple,
      YieldRateUpdatedEvent.OutputTuple,
      YieldRateUpdatedEvent.OutputObject
    >;
    YieldRateUpdated: TypedContractEvent<
      YieldRateUpdatedEvent.InputTuple,
      YieldRateUpdatedEvent.OutputTuple,
      YieldRateUpdatedEvent.OutputObject
    >;
  };
}
